### ISSUE TITLE
bu rasm img bilan berilmaydi pseudoelement bilan berishiz kerak edi

### ISSUE THREAD

**Issue by AbdunazarovU** [NurmuhammadovHojiakbar/zednit#1]
https://github.com/NurmuhammadovHojiakbar/zednit/blob/33b6b82ecb80ba990f2f5344faa12cb90b2d7ff4/index.html#L55

**Comment by NurmuhammadovHojiakbar** [comment]
Boshida shunday qildim keyin images bilan berishni maqul ko'rdim

**Comment by NurmuhammadovHojiakbar** [comment]
ho'p

**Comment by NurmuhammadovHojiakbar** [comment]
Hop
